### ISSUE TITLE
DigitalOcean provider ignores DO_AUTH_TOKEN env var

### ISSUE THREAD

**Issue by Aeron** [caddyserver/tls.dns#4]
### Steps to reproduce

+ Build Caddy 2.0.0-beta.20 image with `tls.dns.digitalocean` module support:
   
   ```dockerfile
   # Builder
   FROM caddy/caddy:2.0.0-beta.20-builder AS builder-extra

   RUN caddy-builder github.com/caddyserver/tls.dns/providers/digitalocean

   # Actual image
   FROM caddy/caddy:2.0.0-beta.20

   COPY --from=builder-extra /usr/bin/caddy /usr/bin/caddy

   COPY Caddyfile /etc/caddy/Caddyfile
   ```

   ```sh
   docker build -t caddy/caddy-do:latest .
   ```

+ Specify a DNS challenge provider in a Caddyfile:

   ```Caddyfile
   tls {
       dns digitaloceal
   }
   ```

+ Run the image with `AUTH_TOKEN` env var:

   ```sh
   docker run -it --rm -p 80:80 -p 443:443 -e DO_AUTH_TOKEN=$DO_AUTH_TOKEN caddy/caddy-do:latest
   ```

### Expected

Works its magic, runs as expected.

### Actual

Stops with the following output:

```console
<timestamp> INFO using provided configuration {"config_file": "/etc/caddy/Caddyfile", "config_adapter": "caddyfile"}
<timestamp> [INFO][cache:0xc0007a4320] Started certificate maintenance routine
<timestamp> [INFO][cache:0xc0007a4320] Stopped certificate maintenance routine
run: loading initial config: loading new config: loading tls app module: provision tls: provisioning automation policy 0: loading TLS automation management module: loading module 'acme': provision tls.issuance.acme: making DNS provider: digitalocean: credentials missing
```

### Notes

The repo’s README [states](https://github.com/caddyserver/tls.dns#using-them-in-caddy) it’s fine to use environment variables (BTW, [configure the DNS challenge](https://caddyserver.com/docs/json/apps/tls/automation/policies/management/acme/challenges/) goes nowhere). Related LEGO [documentation](https://go-acme.github.io/lego/dns/digitalocean/#credentials) explicitly defines `DO_AUTH_TOKEN` as an env var name to use.

**The only way to make it work** is to use a JSON format configuration and specify `.apps.tls.automation.policies[0].issuer.challenges.dns.auth_token` value manually.

Caddy is aware of `DO_AUTH_TOKEN` env var, as it exists in `caddy environ` command results.

This issue can be reproduced entirely without using Docker.

### References

Related to caddyserver/caddy#2855.

**Comment by mholt** [comment]
Yeah... this is why all the open PRs are on hold right now and only a few DNS providers were migrated as experiments, it turns out that lego's exported API and  the way it uses env variables is not compatible with Caddy 2's requirements. So I need to figure that out, but probably after the 2.0 release.

**Comment by mholt** [comment]
@Aeron @MrGreenTea @Ebrithil95

This repository is being decomissioned in favor of [caddy-dns modules](https://github.com/caddy-dns) which implement the new [libdns interfaces](https://github.com/libdns/libdns).

If you are able, **please [help port the old providers to libdns](https://caddy.community/t/writing-new-dns-provider-modules-for-caddy/7786?u=matt) so they can be used in Caddy 2.** In the meantime, you may use [lego-deprecated](https://github.com/caddy-dns/lego-deprecated) which supports all 75+ DNS providers to get up and running quickly.

Thank you for understanding!
