### ISSUE TITLE
acme complains about empty token/email with env variables set

### ISSUE THREAD

**Issue by MrGreenTea** [caddyserver/tls.dns#5]
I am trying to incorporate caddy 2 into my docker-compose setup. For that I need the cloudflare dns challenge.
In my docker-compose.yml I set the required 

```yaml
environment:
      CF_API_EMAIL: "contact@example.com"
      CF_API_KEY: "XXXXXXXX"
```

But when trying to start caddy, I get
```
making DNS provider: cloudflare: invalid credentials: key & email must not be empty
```

The Caddyfile looks like this:
```
example.com {
  tls {
    dns cloudflare
  }
  respond "Hello, world!"
}

```

What am I missing? Any and all help would be appreciated.
I am using `caddy/caddy:latest` as an image building it from this Dockerfile:
```Dockerfile
FROM caddy/caddy:builder AS builder

RUN caddy-builder github.com/caddyserver/tls.dns/providers/cloudflare

FROM caddy/caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

**Comment by mholt** [comment]
Yep... same as #4 and is why no new PRs are being merged for the time being.
